version: 0.2

phases:
  pre_build:
    commands:
      - echo Init submodules
      - git submodule update --init --recursive
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s9j5x8n9
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/s9j5x8n9/auto-mods-creator:$CODEBUILD_BUILD_NUMBER -f Docker/Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/s9j5x8n9/auto-mods-creator:$CODEBUILD_BUILD_NUMBER